Repository mbta/dotcom, pull requests merged in 2019-12, with the labels that each got.

#294 Add holidays for 2020 and 2021
  apps/holiday/lib/repo.ex
  apps/holiday/test/repo_test.exs
  apps/site/test/site_web/controllers/schedule_controller_test.exs
Labels: needs dev review

#307 Omit no-school services
  apps/site/lib/site_web/controllers/schedule/line_controller.ex
  apps/site/test/site_web/controllers/schedule/line_controller_test.exs
Labels: needs dev review

#305 Omit services that are subsets of other services
  apps/site/lib/site_web/controllers/schedule/line_controller.ex
  apps/site/test/site_web/controllers/schedule/line_controller_test.exs
Labels: needs design review, needs dev review

#309 Tell bots not to index line page with date param
  apps/site/assets/static/robots.txt
Labels: dev review

#315 Adjust style and behavior of Photo Gallery component
  apps/site/assets/css/_photo-gallery.scss
  apps/site/assets/js/photo-gallery.js
Labels: needs dev review, needs product review

#313 Fix missing stops in Schedule Finder origin picker
  apps/site/lib/site_web/controllers/schedule/line.ex
  apps/site/lib/site_web/controllers/schedule/line_controller.ex
Labels: needs design review

#318 Allow a single project/project_update teaser in ContentList
  apps/cms/lib/partial/paragraph/content_list.ex
  apps/cms/test/paragraph/content_list_test.exs
Labels: needs dev review

#320 Schedules call to /api/teasers should use array value for :type
  apps/site/lib/site_web/controllers/mode_controller.ex
Labels: needs dev review

#321 Fix CMS paragraph order being scrambled
  apps/util/lib/util.ex
  apps/util/test/async_assign_test.exs
  apps/util/test/util_test.exs
Labels: needs dev review
