Repository mbta/dotcom, pull requests merged in 2019-08, with the labels that each got.

#120 Redesigned "More Projects" list
  apps/content/lib/teaser.ex
  apps/site/assets/css/_project-update.scss
  apps/site/assets/static/images/project-image-placeholder.png
  apps/site/assets/ts/helpers/__tests__/icon-test.ts
  apps/site/assets/ts/helpers/icon.tsx
  apps/site/assets/ts/projects-entry.ts
  apps/site/assets/ts/projects/__tests__/MoreProjectsRow.tsx
  apps/site/assets/ts/projects/__tests__/MoreProjectsTableTest.tsx
  apps/site/assets/ts/projects/__tests__/__snapshots__/MoreProjectsRow.tsx.snap
  apps/site/assets/ts/projects/__tests__/__snapshots__/MoreProjectsTableTest.tsx.snap
  apps/site/assets/ts/projects/components/Image.tsx
  apps/site/assets/ts/projects/components/MoreProjectsRow.tsx
  apps/site/assets/ts/projects/components/MoreProjectsTable.tsx
  apps/site/assets/ts/projects/components/Project.tsx
  apps/site/assets/ts/projects/components/Route.tsx
  apps/site/assets/ts/projects/components/RouteIcon.tsx
  apps/site/assets/ts/projects/projects-loader.tsx
  apps/site/assets/webpack.config.base.js
  apps/site/lib/site_web/controllers/project_controller.ex
  apps/site/lib/site_web/templates/project/_all_projects.html.eex
  apps/site/lib/site_web/templates/project/index.html.eex
  apps/site/react_renderer/app.js
Labels: dev review

#130 Timetable | Use headsign for nil stops
  apps/site/lib/site_web/controllers/schedule/timetable_controller.ex
  apps/site/test/site_web/controllers/schedule/timetable_controller_test.exs
Labels: dev review

#131 Timetable | Don't calculate tooltip data when it's not today
  apps/site/lib/site_web/controllers/schedule/timetable_controller.ex
  apps/site/test/site_web/controllers/schedule/timetable_controller_test.exs
Labels: dev review

#133 Prevent empty sidebar right from rendering
  apps/site/lib/site_web/views/page_content_view.ex
  apps/site/test/site_web/views/page_content_view_test.exs
Labels: dev review

#128 Project Index | Update breadcrumbs
  apps/site/lib/site_web/controllers/project_controller.ex
  apps/site/test/site_web/controllers/cms_controller_test.exs
Labels: dev review

#137 Move typescript defs out of tsx file (no jsx)
  apps/site/assets/ts/projects/__tests__/MoreProjectsTableTest.tsx
  apps/site/assets/ts/projects/components/Image.tsx
  apps/site/assets/ts/projects/components/MoreProjectsRow.tsx
  apps/site/assets/ts/projects/components/MoreProjectsTable.tsx
  apps/site/assets/ts/projects/components/Route.tsx
  apps/site/assets/ts/projects/components/__projects.d.ts
Labels: dev review

#139 capture more fullstory sessions
  apps/site/assets/js/fullstory.js
Labels: dev review

#138 correction to ferry ticket description
  apps/fares/lib/fare.ex
  apps/fares/lib/fare_info.ex
  apps/fares/lib/format.ex
  apps/site/lib/site/content_rewriters/liquid_objects/fare.ex
  apps/site/lib/site_web/templates/cms/paragraph/_fare_card.html.eex
  apps/site/test/site_web/views/helpers_test.exs
Labels: dev review

#122 Realtime Schedule API
  apps/predictions/lib/repo.ex
  apps/routes/lib/parser.ex
  apps/routes/lib/repo.ex
  apps/site/lib/site/realtime_schedule.ex
  apps/site/lib/site_web/controllers/realtime_schedule_api.ex
  apps/site/lib/site_web/router.ex
  apps/site/test/site/realtime_schedule_test.exs
  apps/site/test/site_web/controllers/realtime_schedule_api_test.exs
Labels: dev review

#140 Projects Index | Text Partial
  apps/cms/lib/api/static.ex
  apps/cms/lib/repo.ex
  apps/cms/priv/_paragraph.json
  apps/cms/test/api/static_test.exs
  apps/cms/test/repo_test.exs
  apps/site/lib/site_web/controllers/project_controller.ex
  apps/site/lib/site_web/templates/project/index.html.eex
  apps/site/lib/site_web/views/paragraph_view.ex
  apps/site/lib/site_web/views/partial_view.ex
  apps/site/lib/site_web/views/project_view.ex
  apps/site/test/site_web/controllers/project_controller_test.exs
  apps/site/test/site_web/views/partial_view_test.exs
Labels: dev review

#134 Migrate project template / fix missing project sidebar elements
  apps/cms/lib/api/static.ex
  apps/site/lib/site_web/controllers/cms_controller.ex
  apps/site/lib/site_web/controllers/project_controller.ex
  apps/site/lib/site_web/router.ex
  apps/site/lib/site_web/templates/cms/page/_page.html.eex
  apps/site/lib/site_web/templates/cms/page/_project.html.eex
  apps/site/lib/site_web/templates/project/_contact.html.eex
  apps/site/lib/site_web/templates/project/_diversions.html.eex
  apps/site/lib/site_web/templates/project/_downloads.html.eex
  apps/site/lib/site_web/templates/project/_updates.html.eex
  apps/site/lib/site_web/templates/project/show.html.eex
  apps/site/lib/site_web/views/helpers/cms_router_helpers.ex
  apps/site/lib/site_web/views/page_content_view.ex
  apps/site/lib/site_web/views/project_view.ex
  apps/site/test/site_web/controllers/cms_controller_test.exs
  apps/site/test/site_web/controllers/project_controller_test.exs
  apps/site/test/site_web/views/cms_router_helpers_test.exs
  apps/site/test/site_web/views/project_contact_test.exs
  apps/site/test/site_web/views/project_view_test.exs
Labels: dev review

#142 Project Index | Project Banner
  apps/site/assets/css/_banner.scss
  apps/site/assets/ts/helpers/css.ts
  apps/site/assets/ts/helpers/date.ts
  apps/site/assets/ts/projects/__tests__/BannerTest.tsx
  apps/site/assets/ts/projects/__tests__/MoreProjectsTableTest.tsx
  apps/site/assets/ts/projects/__tests__/__snapshots__/BannerTest.tsx.snap
  apps/site/assets/ts/projects/components/Banner.tsx
  apps/site/assets/ts/projects/components/MoreProjectsRow.tsx
  apps/site/assets/ts/projects/components/MoreProjectsTable.tsx
  apps/site/assets/ts/projects/components/__projects.d.ts
  apps/site/assets/ts/projects/projects-loader.tsx
  apps/site/assets/ts/stop/components/RoutePillList.tsx
  apps/site/lib/site_web/controllers/project_controller.ex
  apps/site/lib/site_web/templates/page/_banner.html.eex
  apps/site/lib/site_web/templates/project/_banner.html.eex
  apps/site/lib/site_web/templates/project/_featured_project.html.eex
  apps/site/lib/site_web/templates/project/index.html.eex
  apps/site/lib/site_web/views/helpers/cms_router_helpers.ex
  apps/site/lib/site_web/views/page_view.ex
  apps/site/react_renderer/app.js
Labels: dev review

#143 Allow basic pages tagged with route to appear in promo slot
  apps/site/lib/site_web/controllers/schedule/cms.ex
Labels: dev review, needs content review

#145 Schedule Finder | Duplicate stops
  apps/site/lib/site_web/controllers/schedule/line_controller.ex
Labels: dev review

#146 Feature projects on new project index
  apps/site/assets/css/_project-update.scss
  apps/site/assets/ts/projects/__tests__/FeaturedProjectsList.tsx
  apps/site/assets/ts/projects/__tests__/RoutePillListTest.tsx
  apps/site/assets/ts/projects/__tests__/__snapshots__/FeaturedProjectsList.tsx.snap
  apps/site/assets/ts/projects/components/FeaturedProject.tsx
  apps/site/assets/ts/projects/components/FeaturedProjectsList.tsx
  apps/site/assets/ts/projects/components/FeaturedProjectsRow.tsx
  apps/site/assets/ts/projects/components/MoreProjectsRow.tsx
  apps/site/assets/ts/projects/components/RouteIcon.tsx
  apps/site/assets/ts/projects/components/RoutePill.tsx
  apps/site/assets/ts/projects/components/RoutePillList.tsx
  apps/site/assets/ts/projects/projects-loader.tsx
  apps/site/lib/site_web/templates/project/_featured_projects.html.eex
  apps/site/lib/site_web/templates/project/index.html.eex
Labels: dev review, needs design review

#149 Add cdn.knightlab.com to EmbeddedMedia
  apps/site/lib/site/content_rewriters/embedded_media.ex
Labels: dev review

#147 Support paragraphs on Project Update pages
  apps/cms/lib/api/static.ex
  apps/cms/lib/page/project_update.ex
  apps/cms/priv/repo/project-updates.json
  apps/cms/test/api/static_test.exs
  apps/site/lib/site_web/controllers/cms_controller.ex
  apps/site/lib/site_web/controllers/project_controller.ex
  apps/site/lib/site_web/router.ex
  apps/site/lib/site_web/templates/cms/page/_project_update.html.eex
  apps/site/lib/site_web/views/page_content_view.ex
  apps/site/test/site_web/controllers/cms_controller_test.exs
  apps/site/test/site_web/controllers/project_controller_test.exs
Labels: dev review

#152 Fix alert icons in Transit Near Me
  apps/site/lib/site/transit_near_me.ex
  apps/site/test/site/transit_near_me_test.exs
Labels: dev review

#157 Schedules | Sort pruned schedules
  apps/site/lib/site_web/controllers/schedule/schedule_api.ex
Labels: dev review

#160 realtime API bug fixes
  apps/site/lib/site/realtime_schedule.ex
  apps/site/test/site/realtime_schedule_test.exs
Labels: dev review

#161 IE11: add fetch polyfilll to app.js and fix up response.body
  apps/site/assets/js/app-entry.js
  apps/site/assets/ts/projects/components/MoreProjectsTable.tsx
  apps/site/assets/ts/stop/stop-loader.tsx
  apps/site/assets/ts/tnm/transit-near-me-loader.tsx
Labels: dev review

#163 Algolia Index update: Handle route id of Green
  apps/algolia/lib/algolia/routes.ex
Labels: dev review

#166 Support updated CMS API datetime RFC3339 format
  apps/cms/lib/helpers.ex
  apps/site/test/site_web/views/cms_view_test.exs
Labels: dev review

#136 instrumentation for nodejs process
  apps/site/lib/site/react/worker.ex
  apps/site/react_renderer/app.js
  apps/site/test/site/lib/react_test.exs
Labels: dev review

#167 support {{ route:x }} liquid replacements
  apps/site/lib/site/content_rewriters/liquid_objects.ex
  apps/site/lib/site/content_rewriters/liquid_objects/route.ex
  apps/site/test/site/content_rewriters/liquid_objects/route_test.exs
  apps/site/test/site/content_rewriters/liquid_objects_test.exs
Labels: dev review

#172 Fix readability of weekend-selected dates on calendar
  apps/site/assets/css/_schedule.scss
Labels: dev review

#175 Fix broken Stops test due to API updates
  apps/stops/test/api_test.exs
Labels: dev review

#174 Don't hard-limit diversion teasers in content lists
  apps/cms/lib/partial/paragraph/content_list.ex
Labels: dev review

#176 Projects | correct date regardless of client timezone
  apps/site/assets/ts/helpers/date.ts
Labels: dev review

#159 Transit Near Me | Use realtime data API
  apps/site/assets/css/_loading-spinner.scss
  apps/site/assets/css/_schedule-page.scss
  apps/site/assets/css/app.scss
  apps/site/assets/package-lock.json
  apps/site/assets/package.json
  apps/site/assets/ts/__v3api.d.ts
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceSelectorTest.tsx.snap
  apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx
  apps/site/assets/ts/tnm/__tests__/RoutesSidebarTest.tsx
  apps/site/assets/ts/tnm/__tests__/StopWithRoutesCardTest.tsx
  apps/site/assets/ts/tnm/__tests__/StopsSidebarTest.tsx
  apps/site/assets/ts/tnm/__tests__/TransitNearMeMapTest.tsx
  apps/site/assets/ts/tnm/__tests__/TransitNearMeTest.tsx
  apps/site/assets/ts/tnm/__tests__/__snapshots__/RoutesSidebarTest.tsx.snap
  apps/site/assets/ts/tnm/__tests__/__snapshots__/StopWithRoutesCardTest.tsx.snap
  apps/site/assets/ts/tnm/__tests__/__snapshots__/StopsSidebarTest.tsx.snap
  apps/site/assets/ts/tnm/__tests__/__snapshots__/TransitNearMeTest.tsx.snap
  apps/site/assets/ts/tnm/__tests__/helpers/testUtils.ts
  apps/site/assets/ts/tnm/__tests__/realtimeData.json
  apps/site/assets/ts/tnm/__tests__/state.json
  apps/site/assets/ts/tnm/__tests__/stateTest.ts
  apps/site/assets/ts/tnm/__tests__/stop-includes-mode-test.ts
  apps/site/assets/ts/tnm/__tests__/tnmData.json
  apps/site/assets/ts/tnm/__tests__/tnmStopData.json
  apps/site/assets/ts/tnm/components/RoutesSidebar.tsx
  apps/site/assets/ts/tnm/components/StopsSidebar.tsx
  apps/site/assets/ts/tnm/components/TransitNearMe.tsx
  apps/site/assets/ts/tnm/components/__tnm.d.ts
  apps/site/assets/ts/tnm/components/leaflet/TransitNearMeMap.tsx
  apps/site/assets/ts/tnm/helpers/process-realtime-data.ts
  apps/site/assets/ts/tnm/helpers/stop-includes-modes.ts
  apps/site/assets/ts/tnm/state.ts
  apps/site/assets/ts/tnm/transit-near-me-loader.tsx
  apps/site/lib/site/realtime_schedule.ex
  apps/site/lib/site/transit_near_me.ex
  apps/site/lib/site_web/controllers/transit_near_me/stops_with_routes.ex
  apps/site/lib/site_web/controllers/transit_near_me_controller.ex
  apps/site/lib/site_web/router.ex
  apps/site/lib/site_web/templates/transit_near_me/index.html.eex
  apps/site/lib/site_web/views/transit_near_me_view.ex
  apps/site/test/predicted_schedule/group_test.exs
  apps/site/test/site/lib/react_test.exs
  apps/site/test/site/realtime_schedule_test.exs
  apps/site/test/site/transit_near_me_test.exs
  apps/site/test/site_web/controllers/transit_near_me/stops_with_routes_test.exs
  apps/site/test/site_web/controllers/transit_near_me_controller_test.exs
  apps/site/test/site_web/views/transit_near_me_view_test.exs
Labels: dev review

#192 use CondensedSchedule in Transit Near Me
  apps/schedules/lib/repo_condensed.ex
  apps/schedules/lib/schedule.ex
  apps/schedules/lib/schedules.ex
  apps/schedules/test/repo_condensed_test.exs
  apps/site/lib/predicted_schedule.ex
  apps/site/lib/site/realtime_schedule.ex
  apps/site/test/site/realtime_schedule_test.exs
Labels: WIP

#148 Redirect routes eliminated by Better Bus Project
  apps/site/lib/site_web/router.ex
  apps/site/test/site_web/router_test.exs
Labels: on hold

#150 Change 424 bus from inner express to local
  apps/fares/lib/fares.ex
Labels: on hold
