Repository mbta/dotcom, pull requests merged in 2019-10, with the labels that each got.

#234 Projects search facet
  apps/site/assets/js/algolia-autocomplete-with-geo.js
  apps/site/assets/js/algolia-autocomplete.js
  apps/site/assets/js/algolia-embedded-search-options.js
  apps/site/assets/js/algolia-embedded-search.js
  apps/site/assets/js/algolia-facets.js
  apps/site/assets/js/algolia-global-search.js
  apps/site/assets/js/algolia-result.js
  apps/site/assets/js/algolia-results.js
  apps/site/assets/js/test/algolia-result_test.js
  apps/site/assets/js/test/algolia-results_test.js
Labels: dev review, needs design review

#241 Hide CR schedule tab (redirect to timetable)
  apps/site/assets/css/_stop-bubbles.scss
  apps/site/lib/site_web/controllers/schedule/trip_view_controller.ex
  apps/site/lib/site_web/views/schedule_view.ex
  apps/site/test/site_web/views/schedule_view_test.exs
Labels: dev review

#243 disable Credo.Check.Refactor.MapInto, N/A for 1.8+
  config/.credo.exs
Labels: dev review

#239 Adjust fares for Foxboro pilot
  apps/fares/lib/fares.ex
  apps/fares/mix.exs
  apps/site/lib/site/base_fare.ex
  apps/site/lib/site_web/controllers/fare/commuter.ex
  apps/site/lib/site_web/controllers/schedule/schedule_api.ex
  apps/site/lib/trip_info.ex
  apps/site/test/site/lib/base_fare_test.exs
  apps/site/test/site_web/controllers/fare/commuter_test.exs
  apps/zones/priv/crzones.csv
Labels: dev review

#240 Foxboro | Franklin timetable "via Fairmount Line"
  apps/site/lib/site_web/controllers/schedule/timetable_controller.ex
  apps/site/lib/site_web/templates/schedule/_timetable.html.eex
  apps/site/test/site_web/controllers/schedule/timetable_controller_test.exs
  apps/site/test/site_web/controllers/schedule_controller_test.exs
Labels: dev review, needs design review

#246 Foxboro | Frank in CR-Fairmount timetable
  apps/site/lib/site_web/controllers/schedule/timetable_controller.ex
  apps/site/lib/site_web/templates/schedule/_timetable.html.eex
  apps/site/lib/site_web/views/schedule_view.ex
  apps/site/test/site_web/controllers/schedule/timetable_controller_test.exs
Labels: dev review, needs design review

#251 Test fix: "Franklin Line" -> "Franklin Line/Foxboro Pilot"
  apps/site/test/detailed_stop_group_test.exs
Labels: dev review

#250 Line diagram alerts
  apps/site/assets/ts/schedule/__tests__/LineDiagramTest.tsx
  apps/site/assets/ts/schedule/__tests__/__snapshots__/LineDiagramTest.tsx.snap
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleDirectionTest.tsx.snap
  apps/site/assets/ts/schedule/__tests__/__snapshots__/SchedulePageTest.tsx.snap
  apps/site/assets/ts/schedule/components/LineDiagram.tsx
  apps/site/assets/ts/schedule/components/__schedule.d.ts
  apps/site/lib/site_web/controllers/schedule/line_api.ex
  apps/site/lib/site_web/controllers/schedule/line_controller.ex
  apps/site/test/site_web/controllers/line_api_test.exs
Labels: dev review, needs design review

#253 Table accessibility fix-ups for ScheduleFinder
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleTableTest.tsx.snap
  apps/site/assets/ts/schedule/components/schedule-finder/ScheduleTable.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/TableRow.tsx
Labels: dev review

#252 Rename info tab for CR
  apps/site/assets/css/_schedule.scss
  apps/site/lib/site_web/templates/schedule/_line.html.eex
  apps/site/lib/site_web/views/schedule_view.ex
  apps/site/test/site_web/views/schedule_view_test.exs
Labels: dev review, needs design review

#249 Foxboro | Event Service | Add disclaimer/link to pilot
  apps/site/assets/css/_schedule-page.scss
  apps/site/assets/ts/schedule/__tests__/ScheduleNoteTest.tsx
  apps/site/assets/ts/schedule/__tests__/SchedulePageTest.tsx
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleNoteTest.tsx.snap
  apps/site/assets/ts/schedule/__tests__/__snapshots__/SchedulePageTest.tsx.snap
  apps/site/assets/ts/schedule/components/LineDiagram.tsx
  apps/site/assets/ts/schedule/components/ScheduleNote.tsx
  apps/site/assets/ts/schedule/components/SchedulePage.tsx
  apps/site/assets/ts/schedule/components/__schedule.d.ts
  apps/site/assets/ts/schedule/schedule-loader.tsx
  apps/site/lib/site/schedule_note.ex
  apps/site/lib/site_web/templates/schedule/_direction_select.html.eex
  apps/site/lib/site_web/templates/schedule/_line.html.eex
  apps/site/lib/site_web/templates/schedule/_route_notes.html.eex
  apps/site/lib/site_web/views/helpers/stop_helpers.ex
  apps/site/lib/site_web/views/schedule_view.ex
  apps/site/test/site/lib/schedule_note_test.exs
  apps/site/test/site_web/views/schedule_view_test.exs
Labels: needs design review

#231 Green line route switcher
  apps/site/assets/css/_schedule-direction.scss
  apps/site/assets/ts/schedule/__tests__/ScheduleDirectionTest.tsx
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleDirectionTest.tsx.snap
  apps/site/assets/ts/schedule/components/direction/BusMenu.tsx
  apps/site/assets/ts/schedule/components/direction/GreenLineMenu.tsx
  apps/site/assets/ts/schedule/components/direction/ScheduleDirectionMenu.tsx
  apps/site/assets/ts/schedule/components/direction/menu-helpers.ts
Labels: dev review

#257 Fall 2019 rating change | Test updates
  apps/site/test/site/lib/vehicle_helpers_test.exs
Labels: dev review
