Repository mbta/dotcom, pull requests merged in 2019-07, with the labels that each got.

#70 Update URLs in map helper, remove temporary test changes
  apps/predictions/test/repo_test.exs
  apps/site/lib/site/map_helpers.ex
  apps/site/test/site/lib/react_test.exs
  apps/site/test/site/map_helpers_test.exs
  apps/site/test/site/transit_near_me_test.exs
  apps/site/test/site_web/controllers/schedule/green_test.exs
  apps/site/test/site_web/controllers/schedule_controller_test.exs
Labels: dev review

#58 Add service dropdown to schedule finder
  apps/services/lib/repo.ex
  apps/site/assets/ts/__v3api.d.ts
  apps/site/assets/ts/helpers/__tests__/service-test.ts
  apps/site/assets/ts/helpers/service.ts
  apps/site/assets/ts/schedule/__tests__/ScheduleFinderTest.tsx
  apps/site/assets/ts/schedule/__tests__/ScheduleModalTest.tsx
  apps/site/assets/ts/schedule/__tests__/SchedulePageTest.tsx
  apps/site/assets/ts/schedule/__tests__/UpcomingDeparturesTest.tsx
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleModalTest.tsx.snap
  apps/site/assets/ts/schedule/__tests__/__snapshots__/UpcomingDeparturesTest.tsx.snap
  apps/site/assets/ts/schedule/components/ScheduleFinder.tsx
  apps/site/assets/ts/schedule/components/ScheduleFinderAccordion.tsx
  apps/site/assets/ts/schedule/components/SchedulePage.tsx
  apps/site/assets/ts/schedule/components/__schedule.d.ts
  apps/site/assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx
  apps/site/assets/ts/schedule/schedule-loader.tsx
  apps/site/lib/site_web/controllers/schedule/line_controller.ex
Labels: dev review, prod-review

#72 remove Google maps related JS
  apps/site/assets/js/app.js
  apps/site/assets/js/google-map-class.js
  apps/site/assets/js/google-map.js
  apps/site/assets/js/google-map/helpers.js
  apps/site/assets/js/google-map/icons.js
  apps/site/assets/js/google-map/marker.js
  apps/site/assets/js/google-map/polyline.js
  apps/site/assets/js/google-map/styles.js
  apps/site/assets/js/route-map.js
  apps/site/assets/js/test/google-map-class-test.js
  apps/site/assets/js/test/google-map-marker_test.js
  apps/site/assets/js/test/google-map_test.js
  apps/site/assets/js/test/route-map_test.js
  apps/site/assets/js/trip-planner-results.js
  apps/site/assets/ts/trip-plan-results/components/Itinerary.tsx
Labels: dev review

#78 add services site application
  apps/site/assets/ts/trip-plan-results/components/Itinerary.tsx
  apps/site/mix.exs
Labels: dev review

#86 Remove Header Footer template engine & Ruby & gem sass
  Dockerfile
  README.md
  apps/site/assets/namespaced_header_footer/README.md
  apps/site/assets/namespaced_header_footer/brunch-config.js
  apps/site/assets/namespaced_header_footer/package-lock.json
  apps/site/assets/namespaced_header_footer/package.json
  apps/site/lib/mix/tasks/layout/generate.ex
  apps/site/test/lib/mix/tasks/layout/generate_test.exs
  semaphore/setup.sh
Labels: dev review

#90 Keep redirect [sub] params [if whitelisted]
  apps/content/lib/cms/http_client.ex
  apps/content/test/cms/http_client_test.exs
Labels: dev review

#81 mTicket formatting
  apps/fares/lib/format.ex
  apps/fares/test/format_test.exs
  apps/site/lib/site_web/templates/content/_fare_card.html.eex
  apps/site/lib/site_web/templates/content/_grouped_fare_card.html.eex
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Fares_main_0_xs-narrow.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Fares_main_1_xs-wide.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Fares_main_2_sm-narrow.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Fares_main_3_sm-wide.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Fares_main_4_md.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Fares_main_5_lg.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Fares_main_6_xxl.png
  apps/site/test/site_web/views/content_view_test.exs
  apps/site/test/site_web/views/helpers_test.exs
Labels: dev review

#97 Remove hard-coded H2 from project template
  apps/site/lib/site_web/templates/project/show.html.eex
  apps/site/test/site_web/views/project_view_test.exs
Labels: dev review

#98 :thumb is no longer a JSON property for photos
  apps/content/priv/landing_page_with_all_paragraphs.json
Labels: dev review

#84 Parse teaser end time (events)
  apps/content/lib/teaser.ex
  apps/content/priv/cms/teasers.json
  apps/content/priv/cms/teasers_event.json
  apps/content/test/teaser_test.exs
Labels: dev review

#85 Use Repo.teasers for event index
  apps/site/lib/site_web/controllers/event_controller.ex
  apps/site/lib/site_web/controllers/project_controller.ex
  apps/site/lib/site_web/templates/event/_event_list.html.eex
  apps/site/test/site_web/controllers/project_controller_test.exs
  apps/site/test/site_web/views/project_view_test.exs
Labels: dev review

#96 If ¶s are present, use dynamic sidebar content
  apps/site/lib/site_web/controllers/project_controller.ex
  apps/site/lib/site_web/templates/project/show.html.eex
  apps/site/test/site_web/views/project_view_test.exs
Labels: dev review

#104 Corrected fix for empty content lists
  apps/site/lib/site_web/views/content_view.ex
  apps/site/test/site_web/views/content_view_test.exs
Labels: bug, dev review

#105 dedup services
  apps/site/lib/site_web/controllers/schedule/line_controller.ex
  apps/site/test/site_web/controllers/schedule/line_test.exs
Labels: dev review

#108 Schedules | Fix sorting for Saturday service
  apps/site/lib/site_web/controllers/schedule/schedule_api.ex
Labels: dev review

#106 OpenStreetMaps | Map zoom reset
  apps/site/assets/ts/schedule/components/Map.tsx
Labels: prod-review

#110 Schedule Finder | Trip details from the selected origin
  apps/site/assets/ts/schedule/__tests__/ScheduleTableTest.tsx
  apps/site/assets/ts/schedule/__tests__/ServiceSelectorTest.tsx
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleTableTest.tsx.snap
  apps/site/assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx
  apps/site/lib/site_web/controllers/schedule/schedule_api.ex
  apps/site/test/site_web/controllers/schedule/schedule_api_test.exs
Labels: dev review, prod-review

#112 Fix View Fares link on current schedule page
  apps/site/lib/site_web/templates/schedule/_trip_info.html.eex
Labels: dev review

#107 Schedule Finder: aria-controls fix-up
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleTableTest.tsx.snap
  apps/site/assets/ts/schedule/components/schedule-finder/TableRow.tsx
Labels: dev review

#101 Intelligent / overridable Content List CTAs
  apps/content/lib/cms/static.ex
  apps/content/lib/paragraph/content_list.ex
  apps/site/lib/site_web/templates/content/_content_list.html.eex
  apps/site/lib/site_web/templates/content/_teaser_list.html.eex
  apps/site/lib/site_web/views/content_view.ex
  apps/site/test/site_web/views/content_view_test.exs
Labels: dev review

#113 CR Timetable | add stop name to aria lable for each time
  apps/site/lib/site_web/templates/schedule/_timetable_schedule.html.eex
Labels: dev review

#118 Legacy Support | old site requests should use https
  apps/site/config/config.exs
Labels: dev review

#117 Schedule Finder | Fix stop list for opposite Direction
  apps/site/assets/ts/schedule/__tests__/ScheduleFinderAccordionTest.tsx
  apps/site/assets/ts/schedule/__tests__/ScheduleFinderTest.tsx
  apps/site/assets/ts/schedule/__tests__/SchedulePageTest.tsx
  apps/site/assets/ts/schedule/components/ScheduleFinder.tsx
  apps/site/assets/ts/schedule/components/ScheduleFinderAccordion.tsx
  apps/site/assets/ts/schedule/components/__schedule.d.ts
  apps/site/assets/ts/schedule/components/schedule-finder/OriginModalContent.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx
  apps/site/lib/site_web/controllers/schedule/line_controller.ex
Labels: dev review, prod-review

#121 remove schedule sidebar flag
  apps/site/config/config.exs
  apps/site/lib/site_web/controllers/schedule/line_controller.ex
  apps/site/lib/site_web/templates/schedule/_fares.html.eex
  apps/site/lib/site_web/templates/schedule/_holidays.html.eex
  apps/site/lib/site_web/templates/schedule/_line.html.eex
  apps/site/lib/site_web/templates/schedule/_line_connections.html.eex
  apps/site/lib/site_web/templates/schedule/_line_page_stop_info.html.eex
  apps/site/test/backstop_data/bitmaps_reference/Bus_Map__Info_main_0_xs-narrow.png
  apps/site/test/backstop_data/bitmaps_reference/Bus_Map__Info_main_1_xs-wide.png
  apps/site/test/backstop_data/bitmaps_reference/Bus_Map__Info_main_2_sm-narrow.png
  apps/site/test/backstop_data/bitmaps_reference/Bus_Map__Info_main_3_sm-wide.png
  apps/site/test/backstop_data/bitmaps_reference/Bus_Map__Info_main_4_md.png
  apps/site/test/backstop_data/bitmaps_reference/Bus_Map__Info_main_5_lg.png
  apps/site/test/backstop_data/bitmaps_reference/Bus_Map__Info_main_6_xxl.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Maps_and_Info_Worcester_main_0_xs-narrow.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Maps_and_Info_Worcester_main_1_xs-wide.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Maps_and_Info_Worcester_main_2_sm-narrow.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Maps_and_Info_Worcester_main_3_sm-wide.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Maps_and_Info_Worcester_main_4_md.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Maps_and_Info_Worcester_main_5_lg.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Maps_and_Info_Worcester_main_6_xxl.png
  apps/site/test/site_web/controllers/schedule/line_test.exs
  apps/site/test/site_web/controllers/schedule_controller_test.exs
  apps/site/test/site_web/views/schedule_view_test.exs
Labels: dev review

#116 Repo.teasers should support multiple `type` values
  apps/content/lib/cms/http_client.ex
  apps/content/lib/cms/static.ex
  apps/content/lib/helpers.ex
  apps/content/lib/paragraph/content_list.ex
  apps/content/lib/repo.ex
  apps/content/test/cms/http_client_test.exs
  apps/content/test/cms/static_test.exs
  apps/content/test/paragraph/content_list_test.exs
  apps/content/test/paragraph_test.exs
  apps/content/test/repo_test.exs
  apps/site/lib/css_helpers.ex
  apps/site/lib/site_web/controllers/event_controller.ex
  apps/site/lib/site_web/controllers/mode/hub_behavior.ex
  apps/site/lib/site_web/controllers/news_entry_controller.ex
  apps/site/lib/site_web/controllers/page_controller.ex
  apps/site/lib/site_web/controllers/project_controller.ex
  apps/site/lib/site_web/controllers/schedule/cms.ex
  apps/site/lib/site_web/templates/content/_content_list.html.eex
  apps/site/lib/site_web/views/content_view.ex
  apps/site/test/site_web/controllers/project_controller_test.exs
  apps/site/test/site_web/views/content_view_test.exs
  apps/site/test/site_web/views/partial_view_test.exs
Labels: dev review

#123 Schedules Finder | List of stops from shapes
  apps/site/lib/site_web/controllers/schedule/line.ex
  apps/site/lib/site_web/controllers/schedule/line_controller.ex
  apps/site/lib/site_web/controllers/schedule/schedule_api.ex
Labels: dev review

#125 Schedule Finder | Polish
  apps/site/assets/css/_schedule-page.scss
  apps/site/assets/ts/helpers/__tests__/fetchTest.ts
  apps/site/assets/ts/helpers/__tests__/service-test.ts
  apps/site/assets/ts/helpers/fetch.ts
  apps/site/assets/ts/helpers/service.ts
  apps/site/assets/ts/schedule/__tests__/ScheduleModalTest.tsx
  apps/site/assets/ts/schedule/__tests__/ServiceSelectorTest.tsx
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceSelectorTest.tsx.snap
  apps/site/assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx
Labels: dev review
