Repository mbta/dotcom, pull requests merged in 2020-10, with the labels that each got.

#635 Include the Lechmere shuttle in line diagram
  apps/site/test/site_web/controllers/schedule/line/helpers_test.exs
  apps/stops/lib/route_stop.ex
  apps/stops/test/route_stop_test.exs
Labels: needs design review, needs dev review

#636 Use configuration settings for test expectations
  apps/feedback/test/mailer_test.exs
Labels: needs dev review

#618 (revision) 💈 special line diagram styling for stops diversion-related alerts
  apps/alerts/lib/alert.ex
  apps/alerts/test/alerts_test.exs
  apps/site/assets/css/_schedule-page-line-diagram.scss
  apps/site/assets/ts/models/__tests__/alert-test.ts
  apps/site/assets/ts/models/alert.ts
  apps/site/assets/ts/schedule/components/__schedule.d.ts
  apps/site/assets/ts/schedule/components/__tests__/test-data/lineDiagramData.json
  apps/site/assets/ts/schedule/components/line-diagram/ExpandableBranch.tsx
  apps/site/assets/ts/schedule/components/line-diagram/StopCard.tsx
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/LineTest.tsx
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/StopCardTest.tsx
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/DiagramTest.tsx.snap
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/ExpandableBranchTest.tsx.snap
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramTest.tsx.snap
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramWithStopsTest.tsx.snap
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineTest.tsx.snap
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/StopCardTest.tsx.snap
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/StopListWithBranchesTest.tsx.snap
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/lineDiagramData/simple.json
  apps/site/assets/ts/schedule/components/line-diagram/graphics/Diagram.tsx
  apps/site/assets/ts/schedule/components/line-diagram/graphics/Line.tsx
  apps/site/assets/ts/schedule/components/line-diagram/graphics/Merge.tsx
  apps/site/assets/ts/schedule/components/line-diagram/graphics/graphic-helpers.tsx
  apps/site/lib/site/json_helpers.ex
  apps/site/lib/site_web/controllers/helpers.ex
  apps/site/lib/site_web/controllers/schedule/line/diagram_format.ex
  apps/site/lib/site_web/controllers/schedule/line_api.ex
  apps/site/lib/site_web/controllers/schedule/line_controller.ex
  apps/site/test/site_web/controllers/line_api_test.exs
  apps/site/test/site_web/controllers/schedule/line/diagram_format_test.exs
  apps/site/test/support/diagram_helpers.ex
Labels: needs dev review

#639 Remove Facebook domain verification meta tag
  apps/site/lib/site_web/templates/layout/app.html.eex
Labels: needs dev review

#632 ☎️ Replace Full Name field with First Name and Last Name fields
  apps/site/assets/js/support-form.js
  apps/site/assets/js/test/support-form_test.js
  apps/site/lib/site_web/controllers/customer_support_controller.ex
  apps/site/lib/site_web/templates/customer_support/_form.html.eex
  apps/site/lib/site_web/views/customer_support_view.ex
  apps/site/test/site_web/controllers/customer_support_controller_test.exs
  apps/site/test/site_web/integration/support_form_test.exs
Labels: needs design review, needs dev review

#640 Change "Sustainability" page title to "Climate Change"
  apps/site/lib/site_web/templates/layout/_desktop_menu_more.html.eex
  apps/site/lib/site_web/templates/page/_important_links.html.eex
  apps/site/lib/site_web/templates/static_page/about.html.eex
Labels: needs dev review

#642 ☎️ Add support for CharlieCard or Ticket number
  apps/feedback/lib/mailer.ex
  apps/feedback/lib/message.ex
  apps/feedback/test/mailer_test.exs
Labels: needs dev review

#644 Add Subject field to the customer support form
  apps/site/assets/js/support-form.js
  apps/site/assets/js/test/support-form_test.js
  apps/site/lib/site_web/templates/customer_support/_form.html.eex
  apps/site/lib/site_web/views/customer_support_view.ex
Labels: needs dev review

#645 "CharlieCard or Ticket Number" frontend field
  apps/site/assets/js/support-form.js
  apps/site/assets/js/test/support-form_test.js
  apps/site/lib/site_web/controllers/customer_support_controller.ex
  apps/site/lib/site_web/templates/customer_support/_form.html.eex
Labels: needs design review, needs dev review

#646 Run message body through profanity sanitizer
  apps/site/assets/js/support-form.js
  apps/site/assets/js/test/support-form_test.js
  apps/site/assets/package-lock.json
  apps/site/assets/package.json
Labels: needs dev review

#648 Move confirmation message inside the hidden div
  apps/site/lib/site_web/templates/customer_support/index.html.eex
Labels: needs dev review

#641 Stops | Shuttle Alert should be restricted to affected stations
  apps/site/assets/css/_transit-near-me.scss
  apps/site/assets/ts/__v3api.d.ts
  apps/site/assets/ts/components/StopCard.tsx
  apps/site/assets/ts/components/__tests__/AlertsTest.tsx
  apps/site/assets/ts/models/__tests__/alert-test.ts
  apps/site/assets/ts/models/alert.ts
  apps/site/assets/ts/stop/__tests__/AlertsTabTest.tsx
  apps/site/assets/ts/stop/__tests__/RouteCardTest.tsx
  apps/site/assets/ts/stop/__tests__/StopPageTest.tsx
  apps/site/assets/ts/stop/components/RouteCard.tsx
  apps/site/assets/ts/tnm/components/RouteCard.tsx
Labels: needs design review

#656 Fix for error when trying to convert "1A-2" to integer
  apps/fares/lib/fares.ex
  apps/fares/test/fares_test.exs
Labels: needs dev review

#661 Add a script to assist with creating GitHub releases
  bin/.gitignore
  bin/lib/git.py
  bin/lib/input.py
  bin/lib/tag.py
  bin/release
  docs/DEPLOYMENT.md
Labels: needs dev review
