Repository mbta/dotcom, pull requests merged in 2020-02, with the labels that each got.

#371 Fix React key warnings in new line diagram
  apps/site/assets/ts/schedule/components/line-diagram/ExpandableBranch.tsx
  apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
Labels: needs dev review

#370 🐞 IE11 Line Diagram | Height of certain elements is wrong
  apps/site/assets/css/_schedule-page-line-diagram.scss
  apps/site/assets/ts/schedule/__tests__/__snapshots__/LineDiagramTest.tsx.snap
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleDirectionTest.tsx.snap
  apps/site/assets/ts/schedule/__tests__/__snapshots__/SingleStopTest.tsx.snap
  apps/site/assets/ts/schedule/components/line-diagram/ExpandableBranch.tsx
  apps/site/assets/ts/schedule/components/line-diagram/SingleStop.tsx
Labels: needs design review

#359 Schedule Finder | Reorganize services (date) picker (polish task)
  apps/services/lib/service.ex
  apps/site/assets/ts/__v3api.d.ts
  apps/site/assets/ts/helpers/__tests__/service-test.ts
  apps/site/assets/ts/helpers/date.ts
  apps/site/assets/ts/helpers/service.ts
  apps/site/assets/ts/schedule/__tests__/LineDiagramTest.tsx
  apps/site/assets/ts/schedule/__tests__/ScheduleDirectionTest.tsx
  apps/site/assets/ts/schedule/__tests__/ScheduleFinderTest.tsx
  apps/site/assets/ts/schedule/__tests__/ScheduleModalTest.tsx
  apps/site/assets/ts/schedule/__tests__/SchedulePageTest.tsx
  apps/site/assets/ts/schedule/__tests__/ServiceOptGroupTest.tsx
  apps/site/assets/ts/schedule/__tests__/ServiceOptionTest.tsx
  apps/site/assets/ts/schedule/__tests__/ServiceSelectorTest.tsx
  apps/site/assets/ts/schedule/__tests__/SingleStopTest.tsx
  apps/site/assets/ts/schedule/__tests__/__snapshots__/LineDiagramTest.tsx.snap
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceOptGroupTest.tsx.snap
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceSelectorTest.tsx.snap
  apps/site/assets/ts/schedule/__tests__/__snapshots__/SingleStopTest.tsx.snap
  apps/site/assets/ts/schedule/components/ScheduleDirection.tsx
  apps/site/assets/ts/schedule/components/ScheduleFinder.tsx
  apps/site/assets/ts/schedule/components/SchedulePage.tsx
  apps/site/assets/ts/schedule/components/__schedule.d.ts
  apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/ServiceOptGroup.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/ServiceOption.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx
  apps/site/assets/ts/schedule/schedule-loader.tsx
  apps/site/lib/site_web/controllers/schedule/line_controller.ex
  apps/site/lib/site_web/templates/schedule/_line.html.eex
  apps/site/test/site_web/views/schedule_view_test.exs
Labels: needs design review, needs dev review

#377 Deal with no live data for now.
  apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
Labels: needs dev review

#381 Handle missing route in route_to_class function
  apps/site/lib/site_web/views/helpers.ex
  apps/site/test/site_web/views/helpers_test.exs
Labels: needs dev review

#386 Fix delayed CR trips showing as "On time"
  apps/site/lib/predicted_schedule.ex
  apps/site/test/predicted_schedule_test.exs
Labels: needs dev review

#375 Schedules | Search
  apps/site/assets/css/_form.scss
  apps/site/assets/css/_schedule-page-line-diagram.scss
  apps/site/assets/css/_utilities.scss
  apps/site/assets/ts/components/MatchHighlight.tsx
  apps/site/assets/ts/components/SearchBox.tsx
  apps/site/assets/ts/components/__tests__/MatchHighlightTest.tsx
  apps/site/assets/ts/components/__tests__/SearchBoxTest.tsx
  apps/site/assets/ts/components/__tests__/__snapshots__/MatchHighlightTest.tsx.snap
  apps/site/assets/ts/helpers/icon.tsx
  apps/site/assets/ts/hooks/__tests__/useFilteredListTest.tsx
  apps/site/assets/ts/hooks/useFilteredList.ts
  apps/site/assets/ts/schedule/__tests__/__snapshots__/LineDiagramTest.tsx.snap
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleDirectionTest.tsx.snap
  apps/site/assets/ts/schedule/__tests__/__snapshots__/SingleStopTest.tsx.snap
  apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
  apps/site/assets/ts/schedule/components/line-diagram/SingleStop.tsx
  apps/site/test/backstop_data/bitmaps_reference/Bus_Map__Info_main_0_xs-narrow.png
  apps/site/test/backstop_data/bitmaps_reference/Bus_Map__Info_main_1_xs-wide.png
  apps/site/test/backstop_data/bitmaps_reference/Bus_Map__Info_main_2_sm-narrow.png
  apps/site/test/backstop_data/bitmaps_reference/Bus_Map__Info_main_3_sm-wide.png
  apps/site/test/backstop_data/bitmaps_reference/Bus_Map__Info_main_4_md.png
  apps/site/test/backstop_data/bitmaps_reference/Bus_Map__Info_main_5_lg.png
  apps/site/test/backstop_data/bitmaps_reference/Bus_Map__Info_main_6_xxl.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Maps_and_Info_Worcester_main_0_xs-narrow.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Maps_and_Info_Worcester_main_1_xs-wide.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Maps_and_Info_Worcester_main_2_sm-narrow.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Maps_and_Info_Worcester_main_3_sm-wide.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Maps_and_Info_Worcester_main_4_md.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Maps_and_Info_Worcester_main_5_lg.png
  apps/site/test/backstop_data/bitmaps_reference/Commuter_Rail_Maps_and_Info_Worcester_main_6_xxl.png
Labels: needs dev review

#388 Fix current service validity check
  apps/site/assets/ts/helpers/__tests__/service-test.ts
  apps/site/assets/ts/helpers/service.ts
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceOptGroupTest.tsx.snap
Labels: needs dev review

#389 Migrate to Stylelint
  .scss-lint.yml
  .tool-versions
  README.md
  apps/site/assets/.stylelintignore
  apps/site/assets/.stylelintrc
  apps/site/assets/css/_alerts.scss
  apps/site/assets/css/_button-group.scss
  apps/site/assets/css/_carousel.scss
  apps/site/assets/css/_checkbox.scss
  apps/site/assets/css/_customer-support.scss
  apps/site/assets/css/_datepicker.scss
  apps/site/assets/css/_embedded-media.scss
  apps/site/assets/css/_facets.scss
  apps/site/assets/css/_fare-summary.scss
  apps/site/assets/css/_fares.scss
  apps/site/assets/css/_functions.scss
  apps/site/assets/css/_grid-button.scss
  apps/site/assets/css/_header.scss
  apps/site/assets/css/_homepage.scss
  apps/site/assets/css/_layout-cms.scss
  apps/site/assets/css/_mixins.scss
  apps/site/assets/css/_page.scss
  apps/site/assets/css/_radio.scss
  apps/site/assets/css/_schedule-page-line-diagram.scss
  apps/site/assets/css/_schedule-page.scss
  apps/site/assets/css/_schedule.scss
  apps/site/assets/css/_shuttles-page.scss
  apps/site/assets/css/_stop-bubbles.scss
  apps/site/assets/css/_stops-v1.scss
  apps/site/assets/css/_table.scss
  apps/site/assets/css/_timetable.scss
  apps/site/assets/css/_trip-plan-form.scss
  apps/site/assets/css/_trip-plan-results.scss
  apps/site/assets/css/_trip-plan.scss
  apps/site/assets/css/core.scss
  apps/site/assets/css/leaflet.scss
  apps/site/assets/css/project-page.scss
  apps/site/assets/css/style_guide.scss
  apps/site/assets/package-lock.json
  apps/site/assets/package.json
  apps/site/assets/vendor/accessible-date-picker.scss
  apps/site/assets/webpack.config.base.js
  docs/TESTING.md
  package.json
  semaphore/scss_lint.sh
  semaphore/setup.sh
Labels: needs dev review

#393 Mark as "current" if service in rating date range
  apps/site/assets/ts/helpers/service.ts
Labels: needs dev review

#399 Add cleanup function that turns off channel event listeners when component is unmounted
  apps/site/assets/ts/schedule/components/Channel.ts
  apps/site/assets/ts/schedule/components/Map.tsx
Labels: needs dev review
