Repository mbta/dotcom, pull requests merged in 2020-07, with the labels that each got.

#552 Change ALGOLIA_ADMIN_KEY env var to ALGOLIA_WRITE_KEY
  .envrc.template
  README.md
  apps/algolia/config/config.exs
  apps/algolia/config/prod.exs
  apps/algolia/config/test.exs
  apps/algolia/lib/algolia/analytics.ex
  apps/algolia/lib/algolia/api.ex
  apps/algolia/lib/algolia/config.ex
  apps/algolia/lib/algolia/exceptions.ex
  apps/algolia/test/config_test.exs
  apps/site/test/site_web/controllers/search_controller_test.exs
  apps/site/test/site_web/integration/homepage_search_test.exs
  docs/ENVIRONMENT.md
Labels: needs dev review

#535 Cross out skipped/cancelled stops (all modes)
  apps/site/assets/css/_helpers.scss
  apps/site/assets/css/_schedule-page.scss
  apps/site/assets/ts/schedule/__tests__/__snapshots__/TripDetailsTest.tsx.snap
  apps/site/assets/ts/schedule/components/__trips.d.ts
  apps/site/assets/ts/schedule/components/schedule-finder/TripStop.tsx
Labels: needs design review, needs dev review

#555 Revert "Fix location icon"
  apps/site/assets/js/algolia-result.js
  apps/site/assets/js/test/algolia-result_test.js
  apps/site/assets/js/test/algolia-results_test.js
Labels: needs dev review

#549 Include crowding data in data from time_data_for_route_by_stop, fixed
  apps/site/assets/ts/__v3api.d.ts
  apps/site/assets/ts/schedule/__tests__/SingleStopTest.tsx
  apps/site/assets/ts/schedule/__tests__/lineDiagramData/live-data.json
  apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
  apps/site/assets/ts/schedule/components/line-diagram/StopPredictions.tsx
  apps/site/lib/site/transit_near_me.ex
  apps/site/lib/site_web/templates/schedule/_line_page_stop_prediction.html.eex
  apps/site/test/site/transit_near_me_test.exs
Labels: needs dev review

#557 Update tests to reflect changes in the Green Line C branch
  apps/site/test/site_web/controllers/schedule/green_test.exs
  apps/site/test/site_web/controllers/schedule_controller_test.exs
Labels: needs dev review

#532 Add fare calculator widget to fares CMS pages: the prequel
  apps/cms/lib/partial/paragraph.ex
  apps/cms/lib/partial/paragraph/trip_plan_widget.ex
  apps/cms/test/paragraph_test.exs
  apps/site/assets/css/_trip-plan-widget.scss
  apps/site/lib/site_web/templates/cms/paragraph/_trip_plan_widget.html.eex
  apps/site/lib/site_web/templates/partial/_trip_planner_widget.html.eex
  apps/site/lib/site_web/templates/trip_plan/_submit_button.html.eex
  apps/site/test/site_web/views/paragraph_view_test.exs
Labels: needs content review, needs design review, needs dev review

#558 Fix map marker icons for location search results
  apps/site/assets/js/algolia-result.js
  apps/site/assets/js/test/algolia-result_test.js
Labels: needs dev review

#559 Hide realtime status if we don't have a stop name
  apps/site/assets/package-lock.json
  apps/site/assets/package.json
  apps/site/assets/ts/leaflet/components/Map.tsx
  apps/site/assets/ts/schedule/__tests__/VehicleIconsTest.tsx
  apps/site/assets/ts/schedule/components/line-diagram/VehicleIcons.tsx
  apps/site/lib/vehicle_helpers.ex
  apps/site/test/site/lib/vehicle_helpers_test.exs
  apps/stops/lib/stop.ex
Labels: needs design review

#562 Replace Wollaston main nav link with Building a Better T
  apps/site/lib/site_web/templates/layout/_desktop_menu_more.html.eex
Labels: needs dev review

#561 Remove :old_line_diagram flag
  apps/site/config/config.exs
  apps/site/lib/site_web/controllers/schedule/line.ex
  apps/site/lib/site_web/controllers/schedule/line/diagram_helpers.ex
  apps/site/lib/site_web/controllers/schedule/line_api.ex
  apps/site/lib/site_web/templates/schedule/_line.html.eex
  apps/site/lib/site_web/templates/schedule/_line_filters.html.eex
  apps/site/lib/site_web/templates/schedule/_variant_select.html.eex
  apps/site/test/site_web/controllers/schedule/line_test.exs
Labels: needs dev review

#563 Cross out skipped/cancelled stops for CR predictions
  apps/predictions/lib/prediction.ex
  apps/routes/lib/route.ex
  apps/schedules/lib/schedule.ex
  apps/site/assets/ts/__v3api.d.ts
  apps/site/assets/ts/models/__tests__/prediction-test.ts
  apps/site/assets/ts/models/prediction.ts
  apps/site/assets/ts/schedule/__tests__/LineDiagramTest.tsx
  apps/site/assets/ts/schedule/__tests__/SingleStopTest.tsx
  apps/site/assets/ts/schedule/__tests__/StopPredictionsTest.tsx
  apps/site/assets/ts/schedule/__tests__/__snapshots__/StopPredictionsTest.tsx.snap
  apps/site/assets/ts/schedule/components/line-diagram/StopPredictions.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/TripStop.tsx
  apps/site/lib/predicted_schedule.ex
  apps/site/lib/site/transit_near_me.ex
  apps/site/test/site/transit_near_me_test.exs
  apps/stops/lib/stop.ex
Labels: needs dev review

#565 Remove filtering of bus routes for crowding purposes
  apps/routes/lib/route.ex
  apps/routes/test/route_test.exs
  apps/site/lib/site/transit_near_me.ex
Labels: needs dev review

#566 Ensure that the map api doesn't 500 if given bad params
  apps/site/lib/site_web/controllers/schedule/map_api.ex
  apps/site/test/site_web/controllers/schedule/map_api_test.exs
Labels: needs dev review

#560 Show route level alerts in the colored banner
  apps/alerts/lib/alert.ex
  apps/alerts/test/alerts_test.exs
  apps/site/assets/css/_colors.scss
  apps/site/assets/css/_functions.scss
  apps/site/assets/css/_link-block.scss
  apps/site/assets/css/_mixins.scss
  apps/site/assets/css/_transit-near-me.scss
  apps/site/assets/css/app.scss
  apps/site/assets/ts/components/RouteCardHeader.tsx
  apps/site/assets/ts/components/__tests__/RouteCardHeaderTest.tsx
  apps/site/assets/ts/components/__tests__/__snapshots__/RouteCardHeaderTest.tsx.snap
  apps/site/assets/ts/helpers/__tests__/css-test.ts
  apps/site/assets/ts/helpers/__tests__/silver-line-test.ts
  apps/site/assets/ts/helpers/css.ts
  apps/site/assets/ts/helpers/icon.tsx
  apps/site/assets/ts/helpers/silver-line.ts
  apps/site/assets/ts/models/__tests__/alert-test.ts
  apps/site/assets/ts/models/__tests__/route-test.ts
  apps/site/assets/ts/models/alert.ts
  apps/site/assets/ts/models/route.ts
  apps/site/assets/ts/projects/components/MoreProjectsRow.tsx
  apps/site/assets/ts/projects/components/RoutePillList.tsx
  apps/site/assets/ts/schedule/components/line-diagram/SingleStop.tsx
  apps/site/assets/ts/stop/__tests__/__snapshots__/DeparturesTest.tsx.snap
  apps/site/assets/ts/stop/__tests__/__snapshots__/RouteCardTest.tsx.snap
  apps/site/assets/ts/stop/__tests__/__snapshots__/StopPageTest.tsx.snap
  apps/site/assets/ts/stop/components/Departures.tsx
  apps/site/assets/ts/stop/components/Header.tsx
  apps/site/assets/ts/stop/components/RouteCard.tsx
  apps/site/assets/ts/stop/components/StopPage.tsx
  apps/site/assets/ts/stop/components/__stop.d.ts
  apps/site/assets/ts/tnm/__tests__/RouteCardTest.tsx
  apps/site/assets/ts/tnm/__tests__/__snapshots__/RouteCardTest.tsx.snap
  apps/site/assets/ts/tnm/__tests__/__snapshots__/RoutesSidebarTest.tsx.snap
  apps/site/assets/ts/tnm/components/RouteCard.tsx
  apps/site/lib/site/realtime_schedule.ex
  apps/site/lib/site_web/controllers/stop_controller.ex
Labels: needs design review, needs dev review

#567 Do not show crowding if none of the Upcoming Departures for buses has that info
  apps/site/assets/ts/schedule/__tests__/UpcomingDeparturesTest.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/UpcomingDepartures.tsx
Labels: needs dev review

#570 Fix trip details for the generic Green line page
  apps/site/assets/ts/helpers/css.ts
  apps/site/assets/ts/models/__tests__/route-test.ts
  apps/site/assets/ts/models/route.ts
  apps/site/assets/ts/schedule/__tests__/TableRowTest.tsx
  apps/site/assets/ts/schedule/components/line-diagram/SingleStop.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/AccordionRow.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/ScheduleTable.tsx
  apps/site/assets/ts/tnm/__tests__/RoutesSidebarTest.tsx
  apps/site/lib/site_web/controllers/schedule/finder_api.ex
  apps/site/test/site_web/controllers/schedule/finder_api_test.exs
Labels: needs dev review

#572 Update test data to use the current rating
  apps/site/test/site/lib/vehicle_helpers_test.exs
Labels: needs dev review

#571 Hide monthly pass sections for free Logan trips
  apps/site/lib/site_web/templates/trip_plan/_fare_calculator.html.eex
  apps/site/lib/site_web/templates/trip_plan/_itinerary_fares.html.eex
  apps/site/lib/site_web/views/trip_plan_view.ex
  apps/site/test/site_web/views/trip_plan_view_test.exs
  apps/trip_plan/lib/trip_plan/itinerary.ex
  apps/trip_plan/test/itinerary_test.exs
Labels: needs design review, needs dev review

#568 🚍 Stops/Station/TNM | CR | Cross out skipped/cancelled stops
  apps/site/assets/css/_colors.scss
  apps/site/assets/css/_transit-near-me.scss
  apps/site/assets/ts/__v3api.d.ts
  apps/site/assets/ts/components/Headsign.tsx
  apps/site/assets/ts/components/__tests__/HeadsignTest.tsx
  apps/site/assets/ts/components/__tests__/__snapshots__/DirectionTest.tsx.snap
  apps/site/assets/ts/components/__tests__/__snapshots__/HeadsignTest.tsx.snap
  apps/site/assets/ts/helpers/__tests__/prediction-helpers-test.ts
  apps/site/assets/ts/helpers/prediction-helpers.tsx
  apps/site/assets/ts/schedule/__tests__/SingleStopTest.tsx
  apps/site/assets/ts/schedule/__tests__/StopPredictionsTest.tsx
  apps/site/assets/ts/schedule/components/__trips.d.ts
  apps/site/assets/ts/stop/__tests__/__snapshots__/DeparturesTest.tsx.snap
  apps/site/assets/ts/stop/__tests__/__snapshots__/StopPageTest.tsx.snap
  apps/site/assets/ts/tnm/__tests__/__snapshots__/RoutesSidebarTest.tsx.snap
  apps/site/assets/ts/tnm/__tests__/state.json
  apps/site/assets/ts/tnm/helpers/process-realtime-data.ts
  apps/site/lib/site/transit_near_me.ex
  apps/site/test/site/transit_near_me_test.exs
Labels: needs design review, needs dev review

#573 🚍 Stop/Station/TNM | Departure Information
  apps/site/assets/css/_stop-page.scss
  apps/site/assets/css/_transit-near-me.scss
  apps/site/assets/ts/__v3api.d.ts
  apps/site/assets/ts/components/Alerts.tsx
  apps/site/assets/ts/components/__tests__/DirectionTest.tsx
  apps/site/assets/ts/components/__tests__/StopCardTest.tsx
  apps/site/assets/ts/leaflet/__tests__/MapTooltipTest.tsx
  apps/site/assets/ts/models/alert.ts
  apps/site/assets/ts/schedule/__tests__/ConnectionsTest.tsx
  apps/site/assets/ts/schedule/__tests__/LineDiagramTest.tsx
  apps/site/assets/ts/schedule/__tests__/ScheduleDirectionTest.tsx
  apps/site/assets/ts/schedule/__tests__/ScheduleFinderTest.tsx
  apps/site/assets/ts/schedule/__tests__/ScheduleLoaderTest.tsx
  apps/site/assets/ts/schedule/__tests__/ScheduleModalContentTest.tsx
  apps/site/assets/ts/schedule/__tests__/SchedulePageTest.tsx
  apps/site/assets/ts/stop/__tests__/HeaderTest.tsx
  apps/site/assets/ts/stop/__tests__/RouteCardTest.tsx
  apps/site/assets/ts/stop/__tests__/RoutePillListTest.tsx
  apps/site/assets/ts/stop/__tests__/sidebar/AccessibilityTest.tsx
  apps/site/assets/ts/stop/__tests__/stopData.json
  apps/site/assets/ts/stop/components/Departures.tsx
  apps/site/assets/ts/stop/components/RouteCard.tsx
  apps/site/assets/ts/stop/components/StopPage.tsx
  apps/site/assets/ts/stop/components/__stop.d.ts
  apps/site/assets/ts/tnm/__tests__/MapWrapperTest.tsx
  apps/site/assets/ts/tnm/__tests__/MarkerWrapperTest.tsx
  apps/site/assets/ts/tnm/__tests__/RouteCardTest.tsx
  apps/site/assets/ts/tnm/__tests__/RoutesSidebarTest.tsx
  apps/site/assets/ts/tnm/__tests__/TransitNearMeMapTest.tsx
  apps/site/assets/ts/tnm/__tests__/realtimeData.json
  apps/site/assets/ts/tnm/__tests__/state.json
  apps/site/assets/ts/tnm/components/RouteCard.tsx
  apps/site/lib/site/json_helpers.ex
  apps/site/lib/site/realtime_schedule.ex
  apps/site/lib/site_web/controllers/stop_controller.ex
  apps/site/lib/site_web/views/mode_view.ex
  apps/site/test/site/realtime_schedule_test.exs
  apps/site/test/site_web/controllers/stop_controller_test.exs
Labels: needs design review, needs dev review

#574 Add a script for automating production deploys
  .gitignore
  .tool-versions
  README.md
  bin/deploy
  docs/DEPLOYMENT.md
  requirements.txt
Labels: needs dev review

#576 Include URL in list of fields to parse
  apps/alerts/lib/parser.ex
  apps/alerts/test/parser_test.exs
  apps/site/assets/ts/__v3api.d.ts
  apps/site/assets/ts/components/Alerts.tsx
  apps/site/assets/ts/components/__tests__/AlertsTest.tsx
  apps/site/lib/site_web/plugs/banner.ex
Labels: needs dev review

#581 Skip Mattapan test temporarily while the shuttle is running
  apps/site/test/site_web/controllers/schedule_controller_test.exs
Labels: needs dev review
