Repository mbta/dotcom, pull requests merged in 2020-01, with the labels that each got.

#329 Depict branches on schedules line diagram
  apps/site/assets/css/_schedule-page-line-diagram.scss
  apps/site/assets/package-lock.json
  apps/site/assets/package.json
  apps/site/assets/ts/schedule/__tests__/LineDiagramTest.tsx
  apps/site/assets/ts/schedule/__tests__/__snapshots__/LineDiagramTest.tsx.snap
  apps/site/assets/ts/schedule/__tests__/lineDiagramData/outward.json
  apps/site/assets/ts/schedule/__tests__/lineDiagramData/simple.json
  apps/site/assets/ts/schedule/__tests__/lineDiagramWithBranchesData.json
  apps/site/assets/ts/schedule/components/LineDiagram.tsx
  apps/site/assets/ts/schedule/components/direction/ScheduleDirectionMenu.tsx
  apps/site/lib/site_web/controllers/schedule/line.ex
  apps/site/lib/site_web/controllers/schedule/line/diagram_helpers.ex
  apps/site/lib/site_web/controllers/schedule/line_api.ex
Labels: needs design review, needs dev review

#333 Show static ferry map on new line diagram
  apps/site/assets/ts/leaflet/components/__mapdata.d.ts
  apps/site/assets/ts/schedule/__tests__/ScheduleDirectionTest.tsx
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleDirectionTest.tsx.snap
  apps/site/assets/ts/schedule/components/ScheduleDirection.tsx
  apps/site/assets/ts/schedule/schedule-loader.tsx
  apps/site/lib/site_web/templates/schedule/_line.html.eex
Labels: needs design review

#353 Prevent crash when there are no current services for the day
  apps/site/lib/site_web/controllers/schedule/line_controller.ex
  apps/site/test/site_web/controllers/schedule/line_test.exs
Labels: dev review

#365 Render multi-day storm schedule dates correctly
  apps/site/assets/ts/helpers/service.ts
  apps/site/assets/ts/schedule/__tests__/ServiceSelectorTest.tsx
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceSelectorTest.tsx.snap
Labels: needs dev review

#363 Show real-time vehicles on new line diagram
  apps/site/assets/css/_schedule-page-line-diagram.scss
  apps/site/assets/ts/components/ExpandableBlock.tsx
  apps/site/assets/ts/components/__tests__/ExpandableBlockTest.tsx
  apps/site/assets/ts/helpers/icon.tsx
  apps/site/assets/ts/schedule/__tests__/SingleStopTest.tsx
  apps/site/assets/ts/schedule/__tests__/VehicleIconsTest.tsx
  apps/site/assets/ts/schedule/__tests__/__snapshots__/LineDiagramTest.tsx.snap
  apps/site/assets/ts/schedule/__tests__/__snapshots__/SingleStopTest.tsx.snap
  apps/site/assets/ts/schedule/__tests__/lineDiagramData/live-data.json
  apps/site/assets/ts/schedule/components/__schedule.d.ts
  apps/site/assets/ts/schedule/components/line-diagram/ExpandableBranch.tsx
  apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
  apps/site/assets/ts/schedule/components/line-diagram/SingleStop.tsx
  apps/site/assets/ts/schedule/components/line-diagram/VehicleIcons.tsx
  apps/site/lib/site_web/controllers/schedule/line_api.ex
  apps/site/test/site_web/controllers/line_api_test.exs
Labels: needs design review

#368 Add direction and date to CR timetable ARIA label
  apps/site/lib/site_web/controllers/schedule/timetable_controller.ex
  apps/site/lib/site_web/templates/schedule/_timetable.html.eex
  apps/site/test/site_web/views/schedule/timetable_view_test.exs
Labels: needs dev review

#366 Fix new schedules being a blank page in IE11
  apps/site/assets/babel.config.js
  apps/site/assets/tsconfig.webpack.json
  apps/site/assets/webpack.config.base.js
Labels: needs dev review

#369 Fix odd regex in Webpack prod config
  apps/site/assets/webpack.config.prod.js
Labels: needs dev review
