Repository mbta/dotcom, pull requests merged in 2020-05, with the labels that each got.

#459 Add sticky table header to the CR timetable
  apps/site/assets/css/_timetable.scss
  apps/site/assets/js/app.js
  apps/site/assets/js/timetable-stick.js
  apps/site/lib/site_web/templates/schedule/_timetable.html.eex
Labels: needs design review, needs dev review

#465 Show modal in LineDiagram if schedule_direction parameters exist
  apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
Labels: needs design review, needs dev review

#461 Get all services in the current rating into the current optgroup
  apps/site/assets/ts/helpers/__tests__/service-test.ts
  apps/site/assets/ts/helpers/service.ts
  apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceSelectorTest.tsx.snap
  apps/site/assets/ts/schedule/components/schedule-finder/ServiceOptGroup.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx
Labels: needs design review, needs dev review

#472 Avoid server-side rendering warning
  apps/site/lib/site_web/templates/schedule/_line.html.eex
Labels: needs dev review

#477 Get additional teasers from mode
  apps/site/lib/site_web/controllers/schedule/cms.ex
Labels: needs dev review

#480 Show only 5 teasers max in the News section
  apps/site/lib/site_web/controllers/schedule/cms.ex
  apps/site/test/site_web/controllers/schedule/cms_test.exs
Labels: needs dev review

#476 Map & trip details accordion with total itinerary times
  apps/site/assets/css/_trip-plan-results.scss
  apps/site/assets/ts/components/Accordion.tsx
  apps/site/assets/ts/components/__tests__/AccordionTest.tsx
  apps/site/assets/ts/components/__tests__/__snapshots__/AccordionTest.tsx.snap
  apps/site/assets/ts/trip-plan-results/__tests__/__snapshots__/TripPlannerResultsTest.tsx.snap
  apps/site/assets/ts/trip-plan-results/components/Itinerary.tsx
  apps/site/lib/site_web/templates/trip_plan/_itinerary.html.eex
  apps/site/lib/site_web/templates/trip_plan/_itinerary_tab.html.eex
  apps/site/lib/site_web/views/trip_plan_view.ex
  apps/site/test/site_web/views/trip_plan_view_test.exs
Labels: needs dev review

#483 Update human labels for ferry routes
  apps/fares/lib/format.ex
  apps/fares/test/format_test.exs
  apps/site/lib/site_web/controllers/mode/ferry.ex
Labels: needs dev review, needs product review

#486 Remove a test that isn't actually testing our code
  apps/site/test/site_web/controllers/schedule_controller_test.exs
Labels: needs dev review

#485 Update Trip Planner fares URLs for bus and subway
  apps/site/lib/site/trip_plan/related_link.ex
  apps/site/test/site/trip_plan/related_link_test.exs
Labels: needs design review, needs dev review
