Repository mbta/dotcom, pull requests merged in 2022-06, with the labels that each got.

#1313 Access :hide_url via assigns map
  apps/site/lib/site_web/templates/alert/_item.html.eex
Labels: bug

#1314 Change project alerts related alerts logic
  apps/site/lib/site_web/views/page_content_view.ex
  apps/site/test/site_web/views/page_content_view_test.exs
Labels: bug

#1323 Homepage Alerts Section visual changes
  apps/alerts/lib/accessibility.ex
  apps/site/assets/css/_homepage.scss
  apps/site/lib/site_web/templates/page/_alerts.html.eex
  apps/site/lib/site_web/views/page_view.ex
Labels: dev-blue

#1316 Update free transfer logic
  apps/site/lib/site_web/views/trip_compare_view.ex
  apps/site/lib/site_web/views/trip_plan_view.ex
  apps/trip_plan/lib/trip_plan/transfer.ex
  apps/trip_plan/test/transfer_test.exs
Labels: do not merge
