Repository mbta/dotcom, pull requests merged in 2022-09, with the labels that each got.

#1411 Add East Boston ferry fare
  apps/fares/lib/fare_info.ex
  apps/fares/lib/fares.ex
  apps/fares/lib/format.ex
  apps/fares/test/fares_test.exs
  apps/fares/test/format_test.exs
  apps/site/lib/site/content_rewriters/liquid_objects/fare.ex
  apps/site/test/site/content_rewriters/liquid_objects/fare_test.exs
Labels: dev-green

#1414 feat: Remove paper ticket option for East Boston Ferry
  apps/fares/lib/fare_info.ex
  apps/fares/test/format_test.exs
Labels: dev-green

#1417 Restore normal OL service
  apps/site/assets/ts/helpers/__tests__/use-line-suspensions-test.ts
  apps/site/assets/ts/helpers/line-suspensions.ts
  apps/site/assets/ts/schedule/components/ScheduleDirection.tsx
  apps/site/assets/ts/schedule/components/ScheduleLoader.tsx
  apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
  apps/site/assets/ts/schedule/components/line-diagram/LineDiagramWithStops.tsx
  apps/site/assets/ts/schedule/components/line-diagram/StopCard.tsx
  apps/site/assets/ts/schedule/components/line-diagram/StopConnections.tsx
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/LineTest.tsx
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/DiagramTest.tsx.snap
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramTest.tsx.snap
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramWithStopsTest.tsx.snap
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineTest.tsx.snap
  apps/site/lib/site_web/controllers/schedule/line_controller.ex
  apps/site/lib/site_web/controllers/schedule/timetable_controller.ex
  apps/site/lib/site_web/templates/schedule/_line.html.eex
  apps/site/lib/site_web/templates/schedule/_timetable.html.eex
  apps/site/lib/site_web/views/helpers.ex
  apps/site/lib/site_web/views/schedule_view.ex
  apps/v3_api/lib/trips.ex
Labels: dev-blue

#1412 feat(RouteCardHeader): Add copy that makes the card header look clickable
  apps/site/assets/css/_link-block.scss
  apps/site/assets/css/_transit-near-me.scss
  apps/site/assets/ts/components/RouteCardHeader.tsx
  apps/site/assets/ts/components/__tests__/__snapshots__/RouteCardHeaderTest.tsx.snap
  apps/site/assets/ts/stop/__tests__/__snapshots__/DeparturesTest.tsx.snap
  apps/site/assets/ts/stop/__tests__/__snapshots__/RouteCardTest.tsx.snap
  apps/site/assets/ts/stop/__tests__/__snapshots__/StopPageTest.tsx.snap
  apps/site/assets/ts/tnm/__tests__/__snapshots__/RouteCardTest.tsx.snap
  apps/site/assets/ts/tnm/__tests__/__snapshots__/RoutesSidebarTest.tsx.snap
Labels: dev-green

#1418 Improve JS test coverage
  apps/site/assets/package-lock.json
  apps/site/assets/package.json
  apps/site/assets/ts/.eslintrc.js
  apps/site/assets/ts/components/Feedback.tsx
  apps/site/assets/ts/components/GlxOpen.tsx
  apps/site/assets/ts/components/Headsign.tsx
  apps/site/assets/ts/components/Modal.tsx
  apps/site/assets/ts/helpers/__tests__/text-test.ts
  apps/site/assets/ts/hooks/__tests__/useIsGlxOpenTest.tsx
  apps/site/assets/ts/hooks/useIsGlxOpen.ts
  apps/site/assets/ts/models/__tests__/vehicle-test.ts
  apps/site/assets/ts/projects/__tests__/BannerTest.tsx
  apps/site/assets/ts/projects/__tests__/MoreProjectsTableTest.tsx
  apps/site/assets/ts/schedule/components/ScheduleDirection.tsx
  apps/site/assets/ts/schedule/components/ScheduleLoader.tsx
  apps/site/assets/ts/schedule/components/__tests__/ScheduleDirectionTest.tsx
  apps/site/assets/ts/schedule/components/direction/__tests__/BusMenuTest.tsx
  apps/site/assets/ts/schedule/components/direction/__tests__/GreenLineMenuTest.tsx
  apps/site/assets/ts/schedule/components/direction/__tests__/__snapshots__/BusMenuTest.tsx.snap
  apps/site/assets/ts/schedule/components/direction/__tests__/__snapshots__/GreenLineMenuTest.tsx.snap
  apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/DiagramTest.tsx
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/StopCardTest.tsx
  apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/StopCardTest.tsx.snap
  apps/site/assets/ts/schedule/components/line-diagram/graphics/Diagram.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/__tests__/OriginListItemTest.tsx
  apps/site/assets/ts/schedule/components/schedule-finder/__tests__/OriginModalContentTest.tsx
  apps/site/assets/ts/schedule/schedule-loader.tsx
  apps/site/assets/ts/ui/__tests__/accordion-test.ts
Labels: dependencies

#1429 Support viewing route variant stops in Schedule Finder
  apps/site/assets/ts/schedule/components/ScheduleLoader.tsx
  apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
  apps/site/lib/site_web/controllers/schedule/line.ex
  apps/site/test/site_web/controllers/schedule/line_test.exs
Labels: dev-green
