Repository mbta/dotcom, pull requests merged in 2023-02, with the labels that each got.

#1507 Clearer link to alerts
  apps/site/assets/css/_link-block.scss
  apps/site/assets/css/_transit-near-me.scss
  apps/site/assets/ts/components/RouteCardHeader.tsx
  apps/site/assets/ts/stop/components/RouteCard.tsx
Labels: dev-blue

#1516 Check if alerts exists
  apps/site/assets/ts/components/RouteCardHeader.tsx
Labels: dev-blue

#1519 feat(TripPlanner): Add fare estimations for the logan express routes
  apps/fares/lib/fare.ex
  apps/fares/lib/fare_info.ex
  apps/fares/lib/format.ex
  apps/fares/lib/month.ex
  apps/fares/lib/one_way.ex
  apps/fares/test/fare_info_test.exs
  apps/fares/test/one_way_test.exs
  apps/routes/lib/repo.ex
  apps/routes/test/repo_test.exs
Labels: dev-green

#1518 UI Bug | CR Timetable Realtime Train Arrival Icon
  apps/site/assets/css/_timetable.scss
  apps/site/lib/site_web/templates/schedule/_timetable_schedule.html.eex
Labels: WIP, dev-blue

#1525 add pages to website header nav
  apps/site/lib/site_web/views/layout_view.ex
Labels: waiting on cms deploy
