Repository mbta/dotcom, pull requests merged in 2024-04, with the labels that each got.

#1956 fix(AlgoliaSearch): Add support for keyboard navigation
  assets/ts/ui/autocomplete/plugins/algolia.ts
  assets/ts/ui/autocomplete/plugins/geolocation.ts
  assets/ts/ui/autocomplete/plugins/locations.ts
  assets/ts/ui/autocomplete/plugins/popular.ts
Labels: dev-green

#1946 fix(HoursOfOperation): Filter out schedules with same departure and a…
  lib/schedules/hours_of_operation.ex
  test/schedules/hours_of_operation_test.exs
Labels: dev-green

#1978 actually finish cleaning up our old Google Maps code
  README.md
  config/runtime.exs
  lib/dotcom/map_helpers.ex
  lib/dotcom/map_helpers/markers.ex
  lib/dotcom_web/controllers/places_controller.ex
  lib/dotcom_web/controllers/stop/stop_map.ex
  lib/dotcom_web/templates/fare/_nearby_locations.html.eex
  lib/dotcom_web/templates/partial/_hidden_icons.html.eex
  lib/dotcom_web/views/fare_view.ex
  lib/google_maps/google_maps.ex
  lib/google_maps/map_data.ex
  lib/google_maps/map_data/layers.ex
  lib/google_maps/map_data/marker.ex
  lib/google_maps/map_data/path.ex
  lib/google_maps/map_data/symbol.ex
  lib/google_maps/view_helpers.ex
  lib/leaflet/map_data.ex
  lib/picture.ex
  lib/util/position.ex
  test/dotcom/map_helpers/markers_test.exs
  test/dotcom/map_helpers_test.exs
  test/dotcom_web/controllers/trip_plan_controller_test.exs
  test/dotcom_web/views/fare_view_test.exs
  test/location_service/google_maps/google_maps_test.exs
  test/location_service/google_maps/map_data/marker_test.exs
  test/location_service/google_maps/map_data/path_test.exs
  test/location_service/google_maps/map_data_test.exs
  test/trip_plan/geocode/geocode_test.exs
Labels: dev-green

#2002 feat(Polyfill): Remove outdated polyfill
  README.md
  assets/css/_customer-support.scss
  assets/css/_header.scss
  assets/css/_mixins.scss
  assets/css/_people-grid.scss
  assets/css/_photo-gallery.scss
  assets/css/_project.scss
  assets/js/app.js
  assets/js/event-page-setup.js
  assets/js/sentry-filter.js
  assets/js/support-form.js
  assets/js/test/event-page-setup__test.js
  assets/js/test/support-form_test.js
  assets/js/test/view-previous-events__test.js
  assets/package-lock.json
  assets/package.json
  assets/webpack.config.base.js
  lib/dotcom_web/templates/event/_expandable_month.html.eex
  lib/dotcom_web/templates/layout/root.html.eex
Labels: dev-blue

#1982 deps(mix): update open_trip_planner_client to 0.8
  lib/trip_plan/api/open_trip_planner.ex
  mix.exs
  mix.lock
  test/trip_plan/fixture/README.md
  test/trip_plan/fixture/nearby_airport.json
  test/trip_plan/fixture/north_station_to_park_plaza.json
Labels: on hold

#1972 feat(TripPlanner): Walking directions UX update
  assets/css/_spacing.scss
  assets/css/_stop-bubbles.scss
  assets/css/_trip-plan.scss
  assets/css/_typography.scss
  assets/js/stop-bubbles.js
  lib/dotcom/trip_plan/itinerary_row.ex
  lib/dotcom_web/templates/partial/_stop_bubble_container.html.eex
  lib/dotcom_web/templates/schedule/_stop_list_expand_link.html.eex
  lib/dotcom_web/templates/trip_plan/_itinerary.html.eex
  lib/dotcom_web/templates/trip_plan/_itinerary_row.html.eex
  lib/dotcom_web/templates/trip_plan/_itinerary_row_personal.html.eex
  lib/dotcom_web/templates/trip_plan/_itinerary_row_step.html.eex
  lib/dotcom_web/templates/trip_plan/_itinerary_stop.html.eex
  lib/dotcom_web/templates/trip_plan/_itinerary_transfer_stop.html.eex
  lib/dotcom_web/templates/trip_plan/_walk_list_expand_link.html.eex
  lib/dotcom_web/views/trip_plan_view.ex
  lib/mix/tasks/header_footer.ex
  lib/trip_plan/api/open_trip_planner.ex
  lib/trip_plan/leg.ex
  test/dotcom_web/views/schedule/stop_list_view_test.exs
  test/dotcom_web/views/trip_plan_view_test.exs
Labels: needs design review, dev-blue
