Repository mbta/dotcom, pull requests merged in 2024-12, with the labels that each got.

#2244 fix: Remove wheelchair icon from non-accessible stop pages
  assets/ts/stop/__tests__/components/icons/AccessibilityIconTest.tsx
  assets/ts/stop/components/icons/AccessibilityIcon.tsx
Labels: dev-blue

#2248 fix: Make Service.serves_date?/2 use added_stops as a full override
  lib/services/service.ex
  test/dotcom_web/controllers/stop_controller_test.exs
  test/services/service_test.exs
Labels: dev-green

#2263 refactor(ServiceOptGroup): simplified text
  assets/ts/helpers/__tests__/service-test.ts
  assets/ts/helpers/service.ts
  assets/ts/schedule/components/schedule-finder/daily-schedule/DailySchedule.tsx
  assets/ts/schedule/components/schedule-finder/daily-schedule/ServiceOptGroup.tsx
  assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/ServiceOptGroupTest.tsx
  assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/__snapshots__/DailyScheduleTest.tsx.snap
Labels: dev-green

#2265 feat: Update confirmation message for the customer support feedback form
  lib/dotcom_web/templates/customer_support/index.html.eex
Labels: do not merge

#2291 WIP - Make map and results summary sticky
  assets/js/app.js
  assets/js/scroll-to.js
  assets/ts/phoenix-hooks/scroll-into-view.ts
  lib/dotcom_web/components/trip_planner/input_form.ex
  lib/dotcom_web/components/trip_planner/results.ex
  lib/dotcom_web/components/trip_planner/results_summary.ex
  lib/dotcom_web/live/trip_planner.ex
Labels: dev-green

#2292 deps: update mbta_metro to minor version 1
  assets/css/app.scss
  assets/package-lock.json
  assets/tailwind.config.js
  lib/dotcom_web/components/route_symbols.ex
  lib/dotcom_web/components/trip_planner/itinerary_detail.ex
  mix.exs
  mix.lock
Labels: dev-blue

#2293 cleanup(Live.TripPlanner): inputs UI polish
  assets/css/_autocomplete-theme.scss
  assets/tailwind.config.js
  lib/dotcom_web/components/trip_planner/input_form.ex
  lib/dotcom_web/components/trip_planner/results_summary.ex
  mix.exs
  mix.lock
Labels: dev-blue
