Repository mbta/dotcom, pull requests merged in 2025-03, with the labels that each got.

#2410 Add stop headsigns to rail pages
  assets/ts/__v3api.d.ts
  assets/ts/schedule/components/line-diagram/StopPredictions.tsx
  assets/ts/schedule/components/schedule-finder/daily-schedule/TableRow.tsx
  assets/ts/schedule/components/schedule-finder/upcoming-departures/UpcomingDepartures.tsx
  lib/dotcom/transit_near_me.ex
Labels: dev-blue

#2415 fix: Avoid collapsing green line and Mattapan line rows unless needed
  lib/dotcom_web/components/system_status/subway_status.ex
  lib/dotcom_web/live/system_status.ex
  test/dotcom_web/components/system_status/subway_status_test.exs
Labels: dev-green

#2417 feat: add subresource integrity attribute on static assets
  lib/dotcom_web/templates/fare/proposed_sales_locations.html.heex
  lib/dotcom_web/templates/fare/retail_sales_locations.html.heex
  lib/dotcom_web/templates/layout/root.html.heex
  lib/dotcom_web/templates/project/index.html.eex
  lib/dotcom_web/templates/project/index.html.heex
  lib/dotcom_web/templates/schedule/_line.html.eex
  lib/dotcom_web/templates/schedule/_line.html.heex
  lib/dotcom_web/templates/stop/show.html.eex
  lib/dotcom_web/templates/stop/show.html.heex
  lib/dotcom_web/templates/transit_near_me/index.html.eex
  lib/dotcom_web/templates/transit_near_me/index.html.heex
  lib/dotcom_web/views/helpers.ex
Labels: dev-blue

#2419 feat(TimetableController): support new rating trip messages
  lib/dotcom_web/controllers/schedule/timetable_controller.ex
  test/dotcom_web/controllers/schedule/timetable_controller_test.exs
Labels: dev-green

#2422 feat: add nonce to content security policy
  config/runtime.exs
  integration/e2e_tests/security-headers.spec.js
  lib/dotcom_web/content_security_policy.ex
  lib/dotcom_web/plugs/secure_headers.ex
  lib/dotcom_web/plugs/static.ex
  lib/dotcom_web/router.ex
  lib/dotcom_web/templates/layout/_google_translate_plugin.html.heex
  lib/dotcom_web/templates/layout/root.html.heex
  mix.exs
  mix.lock
  test/dotcom_web/plugs/secure_headers_test.exs
Labels: dev-green

#2433 feat: Redirect CR-Middleborough to CR-NewBedford
  lib/dotcom_web/router.ex
Labels: do not merge

#2442 hotfix(ContentSecurityPolicy): implement as a Plug
  lib/dotcom_web/plugs/content_security_policy.ex
  lib/dotcom_web/router.ex
Labels: dev-green

#2452 hotfix(ContentSecurityPolicy): corrected websocket host for iOS15
  lib/dotcom_web/plugs/content_security_policy.ex
Labels: dev-blue
