Repository mbta/dotcom, pull requests merged in 2025-02, with the labels that each got.

#2358 Tell robots to ignore all pages when the domain is mbtace
  lib/dotcom_web/templates/layout/root.html.eex
Labels: dev-green

#2363 feat(autocomplete): in trip planner, auto-select first result on enter
  assets/ts/ui/autocomplete/config.ts
Labels: dev-green

#2357 Remove the TP feedback banner
  lib/dotcom_web/templates/layout/root.html.eex
Labels: do not merge

#2353 feat: Add Hi-Fi system status widget
  lib/dotcom_web/components/route_pills.ex
  lib/dotcom_web/components/system_status/status_label.ex
  lib/dotcom_web/components/system_status/subway_status.ex
  lib/dotcom_web/live/system_status.ex
Labels: dev-blue

#2373 Planned disruptions logic
  config/config.exs
  config/test.exs
  lib/alerts/repo.ex
  lib/alerts/repo/behaviour.ex
  lib/dotcom/alerts.ex
  lib/dotcom/alerts/disruptions/subway.ex
  lib/dotcom/routes.ex
  lib/dotcom/system_status/alerts.ex
  lib/dotcom/utils/date_time.ex
  test/dotcom/alerts/disruptions/subway_test.exs
  test/dotcom/alerts_test.exs
  test/dotcom/routes_test.exs
  test/dotcom/system_status/subway_test.exs
  test/dotcom/utils/date_time_test.exs
  test/dotcom/utils/service_date_time_test.exs
  test/support/mocks.ex
Labels: do not merge

#2387 Planned disruptions display
  lib/dotcom/alerts/disruptions/subway.ex
  lib/dotcom/routes.ex
  lib/dotcom/utils/service_date_time.ex
  lib/dotcom_web/components/alerts.ex
  lib/dotcom_web/components/components.ex
  lib/dotcom_web/components/planned_disruptions.ex
  lib/dotcom_web/components/route_symbols.ex
  lib/dotcom_web/live/system_status.ex
  mix.exs
  mix.lock
  test/dotcom/alerts/disruptions/subway_test.exs
  test/dotcom/utils/service_date_time_test.exs
  test/dotcom_web/components/route_symbols_test.exs
Labels: dev-blue

#2395 feat(AlertController): put new features on the subway alerts page
  lib/alerts/repo.ex
  lib/alerts/repo/behaviour.ex
  lib/dotcom/alerts/disruptions/subway.ex
  lib/dotcom/utils/service_date_time.ex
  lib/dotcom_web/components/alerts.ex
  lib/dotcom_web/components/layouts/alerts_layout.html.heex
  lib/dotcom_web/components/layouts/alerts_page_content_layout.html.heex
  lib/dotcom_web/components/planned_disruptions.ex
  lib/dotcom_web/components/system_status/subway_status.ex
  lib/dotcom_web/controllers/alert_controller.ex
  lib/dotcom_web/live/system_status.ex
  lib/dotcom_web/templates/alert/show.html.heex
  lib/dotcom_web/templates/page/_tabbed_nav.html.heex
  lib/dotcom_web/views/alert_view.ex
  test/dotcom/utils/service_date_time_test.exs
  test/dotcom_web/controllers/alert_controller_test.exs
Labels: dev-green
